a10networks/acos-client

tests/t.py

https://www.python.org/dev/peps/pep-0394/

Change shebang to python2 for PEP 394 compliance

---

acos_client/v30/axapi_http.py
acos_client/v30/file/__init__.py
acos_client/v30/file/ssl_key.py

Also changed minor comment to be more accurate.

Add SSL Key upload

---

README.md

Update README so the example code works.

---

acos_client/v30/slb/template/ssl.py

This fixes the client, I don't know what the right value for server is.

Correctpassphrase property for client ssl template

---

acos_client/v21/admin.py
acos_client/v21/slb/class_list.py
acos_client/v21/system.py

1. system.performance.ge
2. system.admin module

more API support

---

acos_client/v30/slb/service_group.py
acos_client/version.py
setup.py

... I'm embarrassed about having to open this PR.  Still have 3 failures in neutron-lbaas, one of which is a cleanup problem related to the other 2 failing tenant ID tests.

Check existence of kwarg before assuming it's there

---

acos_client/logutils.py
acos_client/v21/axapi_http.py
acos_client/v30/axapi_http.py
tests/unit/test_logutils.py
tox.ini

* Method for cleaning sensitive data from objects
* Currently removes username/password
* Added posargs to tox.ini for nose args

Sensitive data redaction

---

acos_client/v21/action.py
acos_client/v30/action.py

This fixes the problem where we don't write all partitions.   I'm not a fan but it works.  Opening so I can get tests run.

Memory write fix

---

acos_client/v30/responses.py

Another invalid session ID code.

Yet another Exists code

---

acos_client/client.py
acos_client/tests/t.py
acos_client/tests/unit/v30/test_license_manager.py
acos_client/v21/license_manager.py
acos_client/v30/license_manager.py

Provides LicenseManager for v30 and stub for v21

License Manager implementation

---

acos_client/v30/nat.py

I would like to add NAT pool support to AXAPI version 3. It is implemented for version 2 but not for version 3. I have not implemented 'update' method because it seems that device does not support simple update of SNAT pool objects. Fallowing error occurs when update is performed on this kind of object.
"This field cannot be modified at runtime. Please recreate object with this field personality"

NAT pool class for AXAPI v3 has been implemented

---

acos_client/v21/action.py
acos_client/v30/action.py

As the response code changes per device/partition names, the only way to handle it is this terrible, terrible way.

Memory Write resilience

---

acos_client/tests/t.py
acos_client/v21/slb/virtual_port.py

* Fixes t.py by allowing retrieval of virtual ports
* v21 has no "search" method for vports, hence the ugly implementation

v21 Virtual Port "get" implementation

---

acos_client/v21/interface.py

Merge this before #117 and t.py will be a LOT happier.

Interface stub for v2.1

---

acos_client/logutils.py
acos_client/tests/unit/test_logutils.py

Just cleaned up comments and fixed line endings.

Log redact round 2

---

acos_client/tests/t.py
acos_client/tests/unit/test_interfaces.py
acos_client/tests/unit/v21_mocks.py
acos_client/tests/unit/v30/test_interface.py
acos_client/v21/axapi_http.py
acos_client/v21/interface.py

Adds interface capability to v21 - current functionality supports "generic"/ethernet/management interfaces.

v21 Interfaces

---

acos_client/v21/axapi_http.py

fix http conn close

---

tox.ini

This fixes test-running on xenial.

Added basepython commands for environments to fix xenial

---

acos_client/v30/action.py

Fixes https://github.com/a10networks/a10-neutron-lbaas/issues/361

Changed write memory interface to match AXAPI

---

acos_client/v30/base.py
acos_client/v30/slb/service_group.py

Changes in AXAPI require changes in the client

Fixed updating of lb strategies

---

acos_client/tests/unit/v30/test_port.py
acos_client/v30/slb/port.py
acos_client/v30/slb/server.py
setup.py

Slb server port rebase

---

acos_client/v30/slb/hm.py
acos_client/v30/slb/member.py
acos_client/v30/slb/server.py
acos_client/v30/slb/service_group.py
acos_client/v30/slb/virtual_port.py
acos_client/v30/slb/virtual_server.py

Vport config rb

---

acos_client/client.py
acos_client/tests/unit/v30/test_bladeparam.py
acos_client/tests/unit/v30/test_vrrpa.py

This PR fixes various flake8 errors introduced by previous merges.

Fix flake8 errors

---

acos_client/tests/unit/v21/test_slb_virtual_port.py
acos_client/tests/unit/v30/test_slb_virtual_port.py
acos_client/tests/unit/v30/test_slb_virtual_server.py

Responses library seems to be getting a lot of good updates recently, this PR is to fix decorator ordering for tests.

Add additional fixes for responses library update

---

acos_client/v30/slb/template/ssl.py

Fixed bug where cipher-template was not specified

---

acos_client/v30/responses.py

This catches authentication errors.

Reduced specificity of auth err code

---

acos_client/v30/slb/hm.py
acos_client/v30/slb/member.py
acos_client/v30/slb/service_group.py

Reverts a10networks/acos-client#154

Revert "Vport config"

---

acos_client/v30/slb/template/ssl.py

- Modified object parameters with valid keys for client ssl template.
The master branch already has this latest change.

Modified params for template object

---

acos_client/v30/slb/virtual_port.py

Checked creation of http and https virtual ports through a10-octavia.

STACK-1137 add template-http for https virtual ports too

---

acos_client/tests/unit/v30/test_slb_virtual_port.py
acos_client/v30/slb/virtual_port.py

When updating the ipinip, source_nat and use_rcv para, we are facing issue due to invalid check with "if" condition
High
https://a10networks.atlassian.net/browse/STACK-1455
https://a10networks.atlassian.net/browse/STACK-1476
Converted TRUE/FALSE parameters with None parameters, corrected UTs
https://teams.microsoft.com/l/file/0D78BE78-C80E-4047-84BB-DD9A631DC2E2?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FGeneral%2FDevTests%2FSTACK-1476.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:44c2ee5a73ec44a1a6962a86c1c06442@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb

[Stack 1476] correction in ipinip, source_nat and use_recv parameter

---

acos_client/tests/unit/v30/test_slb_virtual_server.py
acos_client/v30/slb/virtual_server.py

Added support for setting loadbalancer description while create and update of loadbalancer sothat it will get reflected on vThunder.
https://a10networks.atlassian.net/browse/STACK-1293
https://github.com/a10networks/a10-octavia/pull/165

STACK-1293: Added support for loadbalancer description.

---

acos_client/v30/system.py

As the name suggests. Allows pulling of system stats

Add 'stats' function to system

---

README.md
acos_client/errors.py
acos_client/tests/unit/v30/test_bladeparam.py
acos_client/tests/unit/v30/test_dns.py
acos_client/tests/unit/v30/test_interface.py
acos_client/tests/unit/v30/test_slb_aflex.py
acos_client/tests/unit/v30/test_vlan.py
acos_client/tests/unit/v30/test_vrrpa.py
acos_client/v30/action.py
acos_client/v30/axapi_http.py
acos_client/v30/responses.py
acos_client/v30/system.py
acos_client/version.py
setup.py

Merged master branch of acos-client into victoria branch
See PR 438 in a10-octavia for further information regarding this:
https://github.com/a10networks/a10-octavia/pull/438

[STACK-2169] Merged master branch to Victoria branch

---

acos_client/tests/unit/test_utils.py
acos_client/utils.py
acos_client/v30/action.py

Merged the latest master branch into experimental/victoria_ff branch
https://a10networks.atlassian.net/browse/STACK-2733
Resolved the merge conflict after merging of the latest master branch into experimental/victoria_ff branch

[STACK-2733]: Merge the latest master branch into experimental/victoria branch

---

acos_client/v30/slb/hm.py

Provided an explicit option for health monitor to specify **override_port** parameter

Provided an explicit option for health monitor to specify override_port parameter 

---

acos_client/v30/slb/hm.py

Merge a10_octavia_1_3_3-d branch to stable/stein for v1.3.3 release

Merge a10_octavia_1_3_3-d branch to stable/stein for v1.3.3 release

---

acos_client/v30/slb/hm.py

Merge master to stable/victoria For:
- STACK-3171
automation test report: http://10.64.3.124/JobListDetail.tcl?OCTAVIA3_062222203751_ytsai_stability_test

Merge master to stable/victoria

---

README.md
acos_client/tests/unit/v30/test_slb_virtual_port.py
acos_client/v30/file/ssl_cert.py
acos_client/v30/file/ssl_key.py
acos_client/v30/slb/__init__.py
acos_client/v30/slb/aflex_policy.py
acos_client/v30/slb/hm.py
acos_client/v30/slb/server.py
acos_client/v30/slb/tcp_proxy.py
acos_client/v30/slb/virtual_port.py
acos_client/version.py
setup.py

Merge a10-octavia v2.1 changes to stable/victoria

Merge a10-octavia v2.1 changes to stable/victoria

---

acos_client/v30/action.py
acos_client/v30/slb/virtual_server.py
acos_client/v30/vrrpa/vrid.py

- Added support for IPv6 load balancer for Rack flow and Automated flow
https://a10networks.atlassian.net/browse/STACK-3421
- Added support for Ipv6 load balancer with Automated flow for both Single and Active Standby topology.
- Fixed VRID issues for DHCP and Patched IP mode.
- Added support for IPv6 load balancer with Rack flow for Shared and L3V partition.

Added support IPv6 static addressing and IPv6 vrid floating ip

---

acos_client/v30/slb/template/ssl.py

Used different SSL aXAPI based on ACOS version. 
1. In _set() method, getting acos-version and using payload for cert and key as per the version requirement.
2. In case of update(), if acos-version >= 5.2.1, passing existing as well as new certificate-list as payload params, as it is required for the update operation in acos 5.2.1 at this moment.

[STACK-3431]: ACOS 5 SSL aXAPI support
