acos_client/v30/axapi_http.py, acos_client/v30/slb/virtual_port.py
Previously we were accepting **kwargs but not setting them properly in the JSON sent to the AX. This fixes it.
I'm open to discussion on whether we should allow this or not.
Part of me thinks it's better to only accept explicit arguments for our AX objects. The other part sees that these objects have a lot of attributes which can unnecessarily muck up code. It also then becomes a little tedious to add new arguments.
If we decide we want to only allow explicitly stated arguments, we can still this to move forward with working code and open an issue to fix it at a later time. I'd be cool with that.
=> Fix implementation of arbitrary kwargs to virtual ports

acos_client/v30/axapi_http.py
Since all of our json has to have that top level placeholder key, it caused all args passed through the default arguments in create to be deleted and replaced with any args (or none if passing `{}`) passed to `axapi_args`.
=> Fix a bug where axapi_args would overwrite all args passed in normal kwargs

acos_client/v30/file/ssl_cert.py, acos_client/v30/file/ssl_key.py, acos_client/v30/slb/template/ssl.py
This way, None is translated to null for JSON purposes. The AXAPI
already doesn't allow "" so there should be no harm in popping off all
values that use that.
=> Replace default ignore argument from None to ""

acos_client/v30/file/ssl_cert.py, acos_client/v30/file/ssl_key.py
Strangely enough, the URIs to update ssl certs and ssl keys is the same as the URI to update (this differs from the other 99% of AXAPI flow).
=> Allow update method to work for ssl-cert/key objects.

acos_client/v30/responses.py, tests/unit/v30/test_responses.py
This was introduced in ACOS 4.0.1.  Functional testing proved that it solved the intended issue.
=> Fix for uncaught NotFound error w/ tests

acos_client/v30/slb/service_group.py, acos_client/version.py, setup.py
When creating a service group, you can either specify a `health-check` or `health-check-disable` field.  You can't use both.  Setting health-check to None resulted in the property not being set in the JSON structure.  This code ensures this gets in to the JSON structure and fixes all tests in neutron-lbaas EXCEPT:
test_create_pool_missing_tenant_id_for_other_tenant
test_create_pool_missing_tenant_id_for_admin
These tests fail due to partition issues that still need to be resolved.
=> Handles health-check inconsistencies

acos_client/client.py, acos_client/v21/axapi_http.py, acos_client/v30/axapi_http.py
Optional timeout parameter to client, because the default is too high.
I've implemented it on v21 only, because we don't use v3 so I can't really test it, but it should be trivial to add.
based on @alonbg [commit](https://github.com/alonbg/acos-client/commit/027370e47862ea64d289a6f55378fe45fb28140d)
=> added optional http timeout for v21

acos_client/v21/slb/aflex.py, acos_client/v21/slb/class_list.py, acos_client/v21/system.py
The issue:
--------------
Uploading classlists & Aflex is not working:
This code is used to reproduce the issue:
```python
from acos_client import Client, AXAPI_21
client = Client('192.168.5.xxx', AXAPI_21, 'admin', 'xxxxx', 443)
client.slb.class_list.upload('test1', 'str a a')
```
This is the HTTP POST that is being sent:
**Note that there are 2 *content-type* headers.**
```
POST /services/rest/v2.1/?format=json&method=slb.class_list.upload&session_id=xxx HTTP/1.1
Host: 192.168.5.xxx
Accept-Encoding: identity
Content-Length: 157
Content-Type: multipart/form-data; boundary=----------AaB03x
Content-type: application/json
User-Agent: ACOS-Client-AGENT-1.2.7
------------AaB03x
Content-Type: application/octet-stream
Content-Disposition: form-data; name="test1"; filename="test1"
str a a …
```
=> Fixes 'ACOSException: 1174' on multipart uploads

tests/unit/test_system.py, tests/unit/v21_mocks.py
MockPair inherits from unittest.TestCase to give it access to assertions that were previously in the mock..  The validation assertion should be moved in to a test and the validated logic moved in to a method that returns the validation result.
=> Updated tests to work with new version of unittest

tests/unit/v30/test_service_group.py
Simple tests for how the v30 service group health check works.
Note that currently it will not pass `'health-check-disable': 1` if it's only passed `health_monitor=""` or `health_monitor=None`.
=> Tests for v30 service group health check

acos_client/v21/action.py
Fixes issue caused when the last element in an LB is deleted and the associated partition is deleted with it.
=> Catch error raised by already-deleted partition

acos_client/tests/t.py, acos_client/v21/slb/member.py, acos_client/v30/slb/member.py, acos_client/v30/slb/server.py
Added "get_opers" methods to members
t.py enhancements
* tests member "get_opers" calls
* wrapped "dirty" (t.py isn't always run against freshly spawned vThunders) logic in try/catch blocks
* wrapped version specific logic in conditional blocks
* Catches NotImplementedError thrown by v2.1 clients that don't yet implement functionality that either isn't implemented in AXAPI or we don't want to have it in acos-client v3.0 (encourage people to use new SDK, it's nicer)
=> v21/30 member opers + t.py resilience

acos_client/tests/t.py, acos_client/tests/unit/v30/test_service_group.py, acos_client/tests/unit/v30/test_virtual_server.py, acos_client/v30/slb/service_group.py, acos_client/v30/slb/virtual_server.py
Adds a method that gives the service groups and virtual servers access to the operational stats on the acos device.
=> Added oper stats

acos_client/v30/axapi_http.py
Observed a timeout of 76 seconds on connecting to a newly launched instance, the new timeout is about twice that. Better logging of number of retries used.
=> Larger timeout for v3 retry loop. 

acos_client/tests/t.py, acos_client/v21/slb/virtual_port.py
Fixes bug with the following error when setting autosnat on a 2.1 vport
params['port']['source_nat_auto'] = int(autosnat)
ERROR neutron_lbaas.services.loadbalancer.plugin KeyError: 'port'
=> 2.1 autosnat vport fix

acos_client/tests/t.py, acos_client/v30/responses.py, acos_client/v30/slb/hm.py
This corrects the problem where an overridden port # is specified but not actually applied.
NOTE: `show run` will indicate that the override is set but will still list the original method-oriented port number in the `http-port` section until updated via the CLI or UI. This does not affect functionality.
=> Health monitor port override - works for all methods

acos_client/v21/axapi_http.py, acos_client/v30/axapi_http.py
This PR adds the following feature to both v21 and v30 of acos_client:
- Closes requests session after attempting to connect to load-balancer
=> Add a definitive session.close() in axapi_http v21 and v30

acos_client/client.py, acos_client/logutils.py, acos_client/tests/unit/test_client.py, acos_client/tests/unit/test_logutils.py, acos_client/tests/unit/v21/test_system.py, acos_client/tests/unit/v30/test_vlan.py, acos_client/tests/unit/v30/test_vrrpa.py, acos_client/v21/axapi_http.py, acos_client/v21/base.py, acos_client/v21/license_manager.py, acos_client/v21/slb/port.py, acos_client/v21/vrrp_a/__init__.py, acos_client/v21/vrrp_a/failover.py, acos_client/v21/vrrp_a/interface.py, acos_client/v21/vrrp_a/vrrp_global.py, acos_client/v30/action.py, acos_client/v30/axapi_http.py, acos_client/v30/base.py, acos_client/v30/license_manager.py, acos_client/v30/nat.py, acos_client/v30/partition.py, acos_client/v30/responses.py, acos_client/v30/slb/member.py, acos_client/v30/vrrpa/vrid.py, tox.ini
Both `Client.client` and its http objects now support `max_retries`. The default is 3.
Both `Client.client` and its http objects now support `timeout`. The default is 5.
The `retry_errno_list` attribute has been removed as it was not being used.
The import `six` was also removed from a few places where it was not used.
Everything else is code cleanup per what the PEP8 and flake8 messages were making noise about.
=> apply feature to control max_retries and timeout behavior

.travis.yml, tox.ini
- Remove tox testing for Python 2.6
- Remove tox testing for Python3.3 as it has reached end of life with no further security updates 
- Update Travis CI to work with multiple tox environments
=> Update Travis CI to support Tox

acos_client/tests/unit/v21/test_partition.py, acos_client/tests/unit/v21/test_slb_health_monitor.py, acos_client/tests/unit/v21/test_slb_service_group.py, acos_client/tests/unit/v21/test_slb_template_cookie_persistence.py, test-requirements.txt
`responses` package has been updated a couple of times this month and revealed an issue with a few tests that were broken.  Those tests have been updated and a minimum version is now in `test-requirements.txt`.
Anyone already using tox for testing will need to rebuild their tox environment:
`tox -r`
=> Update responses package to version 0.10.2 and fix broken tests.

acos_client/v30/responses.py
The previous auth logic looked for a value that no longer exists. This patch accounts for that change and adds the appropriate error # / exception mappings.
=> Corrected "unauthorized" logic to catch new-style auth errors, added error codes

acos_client/tests/unit/v30/test_slb_virtual_server.py, acos_client/v30/slb/virtual_server.py
I added a test to catch the "arp-disable being set bug" and had to update it as we have other tests to ensure what we submit is as expected - it just ensures not specifying arp-disable results in it not being set AT ALL in the resulting JSON. This keeps backwards compatibility with bad versions of AXAPI that see "arp-disable" in the payload and ignore the value on the other side assuming it's true.
=> Correct default arp-disable to False

acos_client/client.py, acos_client/v30/device_context.py, acos_client/v30/route.py
After logging on as shown in the readme, switching contexts can be done using this format:
c.device_context.switch(1,0)
The first parameter is the desired device-id context to switch to and the second is used for changing the obj-slot-id.
When this command is executed A10 device specific changes can be made.
=> Switch device context

acos_client/v30/action.py
Existing code in a10-neutron-lbaas calls `activate_and_write` using
the partition name as the first argument. I changes the order of the
optional arguments in both `activate_and_write` and `write_memory` for
consistency.
Note if you were calling `write_memory` directly from another tool, you will need to switch your partition and destination arguments like `write_memory(partition, destination)`
=> Fix order of optional arguments

acos_client/tests/unit/v30/test_slb_server.py, acos_client/tests/unit/v30/test_slb_service_group.py, acos_client/tests/unit/v30/test_slb_virtual_port.py, acos_client/tests/unit/v30/test_slb_virtual_server.py, acos_client/v30/slb/server.py, acos_client/v30/slb/service_group.py, acos_client/v30/slb/virtual_port.py, acos_client/v30/slb/virtual_server.py
added changes to accept templates from config file as a single JSON
Example: devices = {
"ax1": {
"name": "ax1",
"host": "10.43.12.122",
"port": 443,
"username": "admin",
"password": "a10",
"autosnat": True,
"api_version": "3.0",
"conn-limit": "9000",
"conn-resume": 40000,
"no-dest-nat": 1,
"template-virtual-server": "omkar2",
"templates": {
"virtual-server":{
"template-virtual-server":"sg2",
"template-logging" : "sg2",
"template-policy": "sg2",
"template-scaleout" : "",
},
"virtual-port":{
"template-virtual-port": "sg2",
"template-tcp": "sg2",
"template-policy": "sg2",
"template-scaleout": ""
},
"service-group":{
"template-server": "sg2",
"template-port": "sg2",
"template-policy" : "sg2"
},
"server":{
"template-server":"sg2"
}
}
}
}
=> Template support for all SLB nouns - OM89

acos_client/v30/slb/virtual_port.py
While deleting single L7 Policy from SLB port, the aFlex array comes as empty, resulting in unexpected behavior of "if" condition.
Correction is required to allow empty array as an update in vport update function.
Files Changed:
acos_client/v30/slb/virtual_port.py
=> L7policy Deletion correction 

acos_client/tests/unit/v30/test_slb_server.py, acos_client/v30/slb/hm.py, acos_client/v30/slb/server.py, acos_client/v30/slb/template/persistence.py
- Added ipv4 as an argument for `create` hm method.
- Added UDP and UDP_CONNECT method support for `/health/monitor` API
- Added session persistence support for cookie name
Files changed 
- acos_client/tests/unit/v30/test_slb_server.py
- acos_client/v30/slb/hm.py
- acos_client/v30/slb/server.py 
https://github.com/a10networks/a10-octavia/pull/28
https://github.com/a10networks/a10-octavia/pull/31
[Stack-485](https://a10networks.atlassian.net/browse/STACK-485)
[Stack-482](https://a10networks.atlassian.net/browse/STACK-482)
=> Octavia hm support

acos_client/v30/slb/template/persistence.py
**Non-Customer Highlights:**
Added support for cookie_name for session persistence
**Closes:**
STACK-883
=> STACK-883 : Support for cookie_name for session persistence

acos_client/tests/unit/v30/test_slb_virtual_port.py, acos_client/v30/slb/virtual_port.py
Checked use_rcv_hop for virtual port creation through a10-octavia.
=> STACK-1181 changes to support use-rcv-for-resp

acos_client/tests/unit/v30/test_vrrpa.py, acos_client/v30/vrrpa/vrid.py
**Description**
Added support to configure VRID floating IPs in partition.
**Jira Ticket**
https://a10networks.atlassian.net/browse/STACK-1290
**Related PR**
https://github.com/a10networks/a10-octavia/pull/99
** Technical Approach**
The JSON format of partitions are different that shared partition. Added a optional parameter `is_partition`, based on it, a new JSON is created.
=> [STACK-1290] Added support for partition VRID floating ip configuration

acos_client/v30/action.py
Changes for addition of get_vcs_summary_oper() to get data from endpoint "/vcs/vcs-summary/oper". This API is used by changes done for https://a10networks.atlassian.net/browse/STACK-1365.
=> STACK-1389 changes to get vcs summary oper data

acos_client/tests/unit/v30/test_vrrpa.py, acos_client/v30/vrrpa/vrid.py
- Included `floating-ip` in payload for `create` and `update` of `/vrrp-a/vrid`
- Done testing via TDD only. Need to do functionality test once
[STACK-1217](https://a10networks.atlassian.net/browse/STACK-1217)
=> STACK-1217: Added floating_ip param to vrid create and update API

acos_client/v30/slb/service_group.py
When deleting a health monitor, health_check_disable will also get set. As per expectation, the reference of health monitor should be removed from the service group and health_check_disable attribute should be unaltered.
High
https://a10networks.atlassian.net/browse/STACK-1457
1. Initially checked if removing or setting false or None health_check_disable works, axapi giving an error.
2. Compared service group create API payload with service group update API payload.
3. Statically added the health-check parameter to API payload while updating service group object, worked.
4. Integrated change with the appropriate condition.
1. Tested creation of service group object.
2. Tested update of service group object.
3. Tested delete service group object.
3. Tested the creation of health monitor. …
=> [STACK-1457]: Deleting a health monitor from pool sets pool to health-check-disable instead of just removing the hm association.

acos_client/v30/slb/service_group.py, acos_client/v30/slb/template/templates.py, acos_client/v30/slb/virtual_port.py
Added support for attaching templates from shared partition to virtual-port, service-group and server of a l3v partition.
https://a10networks.atlassian.net/browse/STACK-1559
**For listener:**
- Added support for `template-http-shared` and `shared-partition-http-template` params to attach shared http templates  to a virtual-port.
- Added support for `template-tcp-shared` and `shared-partition-tcp` params to attach shared tcp templates  to a virtual-port.
- Added support for `template-policy-shared` and `shared-partition-policy-template` params to attach shared policy templates  to a virtual-port.
- Added support for `template-virtual-port-shared` and `shared-partition-virtual-port-template` params to attach shared virtual port templates  to a virtual-port.
**For pool:**
- Added support for …
=> STACK-1559: Added support to allow templates to be used from the shared partition

acos_client/tests/unit/v30/test_slb_virtual_server.py, acos_client/v30/slb/virtual_server.py
- When we set loadbalancer description to "" or " ", then the description parameter should not get attached to it i.e it should set to be **None** for the loadbalancer instead of throwing `ACOSException: 1023459374 Input string exceeds permitted length`.
https://a10networks.atlassian.net/browse/STACK-1612
https://github.com/a10networks/a10-octavia/pull/184
- Trimming the description given by user and then validating it.
- If description is "" or " ", then it is set to None
- Given description as "", when an lb is updated with it, the description attaching to the lb is None.
- Given description as " ", when an lb is updated with it, the description attaching to the lb is None.
=> STACK-1612: Handled validations of loadbalancer description

acos_client/tests/unit/v30/test_vrrpa.py, acos_client/v30/vrrpa/vrid.py
Added support for associating multiple floating IPs with a VRID (create / update)
[STACK-1589](https://a10networks.atlassian.net/browse/STACK-1589)
- Modified the `create` and `update` vrrpa vrid functions to take in a list of floating ips instead of a singular one
- Altered `_build_params` function to add each ip in the list to the payload
Requirement: Setup an Active-Standy VRRPA deployment
1. Issue a create command with a single IP ----> only one should be associated
2. Issue a create command with multiple IPs ----> all IPs should be added to the VRID
3. Issue an update command with same IPs as step 2 ----> no change
4. Issue an update command with one IP from step 2/3 removed ----> removed IP not in list (others should remain)
=> [STACK-1589] Added support for associating multiple floating IPs with a VRID

acos_client/tests/unit/v30/test_member.py, acos_client/tests/unit/v30/test_slb_server.py, acos_client/tests/unit/v30/test_slb_service_group.py, acos_client/tests/unit/v30/test_slb_virtual_port.py, acos_client/tests/unit/v30/test_slb_virtual_server.py, acos_client/v30/slb/member.py, acos_client/v30/slb/server.py, acos_client/v30/slb/service_group.py, acos_client/v30/slb/virtual_port.py, acos_client/v30/slb/virtual_server.py
For support of the a10-octavia driver, replace methods (resolving to a PUT call) are required for a number of endpoints surrounding the slb. This way changes in the configuration file can be reflected when updates occur allowing templates to be dissociated. 
[STACK-1647](https://a10networks.atlassian.net/browse/STACK-1647)
[STACK-1651](https://a10networks.atlassian.net/browse/STACK-1651)
[PR 120 in a10-octavia](https://github.com/a10networks/a10-octavia/pull/210)
- Added replace methods which use the PUT request to fully replace the object.
- Refactored set methods to make allow them to be used with replace as well
- Altered the member tests so that they use the responses mock library to be sure PUT was called with proper params
- Removed get requests from create methods. (This was …
=> [STACK 1647][STACK-1651] Add replace methods to address template overwrite needs

acos_client/tests/unit/v30/test_slb_service_group.py, acos_client/v30/slb/service_group.py, acos_client/v30/slb/virtual_server.py
Severity: Critical
When using the `set` command to update an object, a replace method is called which uses the PUT operation to send a payload. The object on the device is fully overwritten by the contents of this payload, so if the reference objects aren't included then they are removed.
Ex: Virtual server vs1 has a listener l1. When a replace is called without l1 in the port list, then l1 is disassociated from vs1.
[STACK-1699](https://a10networks.atlassian.net/browse/STACK-1699)
[STACK-1703](https://a10networks.atlassian.net/browse/STACK-1703)
[PR#217 of a10-octavia](https://github.com/a10networks/a10-octavia/pull/217)
To fix the issue, a GET call is used to access the contents of the object from which the reference objects are extracted. These objects are then added to the payload …
=> [STACK-1703][STACK-1699] Replace methods cause overwrite of connected objects

acos_client/v30/slb/server.py
Severity Level: Critical
Whenever members are updated, the real server ports are removed from associated server objects. This has the extra effect of removing the member object from the service group.
[STACK-1755](https://a10networks.atlassian.net/browse/STACK-1755)
[STACK-1737](https://a10networks.atlassian.net/browse/STACK-1737)
- Added get call for port-list so that real server ports are obtained
[a10-octaiva PR#233](https://github.com/a10networks/a10-octavia/pull/233)
Please see linked PR in a10-octavia for full information regarding requirements of this PR.
N/A
N/A - No testable logic. Just a single get call more or less.
N/A
=> [STACK-1755][STACK-1737] Added port-list reference object attribute to methods for servers

acos_client/v30/slb/hm.py
command: openstack loadbalancer healthmonitor create --delay 3 --timeout 3 --max-retries 2 **--http-method POST** --type HTTP  sg1 --name hm1
result:
```
health monitor 04c35ba9-5d7e-4318-9a2f-72801f52afd1
retry 2
override-port 80
interval 3 timeout 3
method http port 80 expect response-code 200 url POST / postdata abc=1
!
slb server 3d21c_192_168_90_132 192.168.90.132
port 80 tcp
!
slb service-group 1614ea53-9713-4d2d-acab-b151b54eafc1 tcp
health-check 04c35ba9-5d7e-4318-9a2f-72801f52afd1
member 3d21c_192_168_90_132 80
!
slb virtual-server 969066ff-afb9-4967-ab4d-adc9d299c8ec 192.168.91.56
port 80 http
name f54133b3-032f-4d0d-a69e-bfbe82277f07
extended-stats
source-nat auto
service-group 1614ea53-9713-4d2d-acab-b151b54eafc1
!
```
=> [STACK-1654] healthmonitor support POST method

acos_client/tests/unit/v30/test_bladeparam.py, acos_client/tests/unit/v30/test_dns.py, acos_client/tests/unit/v30/test_interface.py, acos_client/tests/unit/v30/test_port.py, acos_client/tests/unit/v30/test_slb_server.py, acos_client/tests/unit/v30/test_slb_service_group.py, acos_client/tests/unit/v30/test_slb_virtual_port.py, acos_client/tests/unit/v30/test_vlan.py, acos_client/tests/unit/v30/test_vrrpa.py, acos_client/v30/axapi_http.py, acos_client/v30/base.py, acos_client/v30/slb/hm.py, acos_client/v30/slb/port.py, acos_client/v30/slb/server.py, acos_client/v30/slb/service_group.py, acos_client/v30/slb/virtual_port.py, acos_client/v30/slb/virtual_server.py
This patch contains:
- flavor support feature
- STACK-1712 Write data migration scripts to go from a10-neutron-lbaas to octavia
Please check detail feature description, testing document in a10-octavia PR:
https://github.com/a10networks/a10-octavia/pull/251
=> Feature/flavor support and acos-client refactor (STACK-1712)

acos_client/version.py, setup.py
**please also check a10-octavia PR: https://github.com/a10networks/a10-octavia/pull/281**
Feature Requirements 
- Requires SNAT Pools to be allocated from Neutron 
- Frequent changes to these pools will occur 
- Restarting configuration file is tedious and can interrupt DevOps tooling workflow 
- Shouldn’t require SNAT Pool to be pre-defined on the ACOS device 
- Adds snat pool option to flavor schema for loadbalancers and can be shared between loadbalancers 
Design Document: https://teams.microsoft.com/l/file/27F4222F-7CDD-421B-8F0C-97A5C60B2B5D?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2FSNAT%20Pools%2FSNAT%20Pools%20Design%20Document.docx& …
=> STACK-1896 Feature Source NAT flavor support

acos_client/tests/unit/v30/test_slb_virtual_port.py, acos_client/v30/slb/virtual_port.py
Severity Level: Medium
Desciption: ACOS5 didn't allow ha-conn-mirror for HTTP, HTTPS and TERMINATED_HTTPS.
https://a10networks.atlassian.net/browse/STACK-1970
ACOS5 didn't allow ha-conn-mirror for HTTP, HTTPS and TERMINATED_HTTPS. So,
- For TCP/UDP, listener will created with ha-conn-mirror
- For HTTP/HTTPS and TERMINATED_HTTPS, listener will be created correctly but without ha-conn-mirror
<pre>
<b>
[a10_controller_worker]
network_driver = a10_octavia_neutron_driver
[listener]
autosnat = True
conn_limit=555000
ha_conn_mirror=True
[health_monitor]
post_data = "abc=1"
[hardware_thunder]
devices = [
{
"project_id": "3d21c71c4e4040599933bda62a76ae2f",
"ip_address": "192.168.90.46",
"username": "admin",
"password": "a10",
"device_name": "ytsai-Thunder"
}
]
</b>
</pre>
1. create listener with …
=> Issue/stack 1970 acos5 not allow ha-conn-mirror for HTTP/HTTPS

acos_client/v30/slb/virtual_port.py
Severity Level: HIGH
Desciption: Can't l7policy delete the latest l7policy on load_balancer.
It is a degrade for previous change on virtual_port.py in acos-client. Previously aflex-scripts is in kwargs (as aflex-scripts) but now it is a named parameter (as aflex_scripts) in acos-client. And for backward compatible I add a check to use aflex-scripts in kwargs if aflex_scripts is not set. But didn't write it correctly. So, for empty list case it will match the condition and goes wrong.
https://a10networks.atlassian.net/browse/STACK-1988
Use 'if aflex_scripts is None' instead in condition check. So, for aflex_scripts = [] case, it will not match the condition.
[optional] just remove this condition and backward compatible.
This bug is not related to configuration
<pre>
<b>N/A</b>
</pre>
1. …
=> Issue/stack 1988 [l7policy_degrade] cannot delete l7policy with action REJECT

acos_client/v30/slb/hm.py
Severity Level: HIGH
Desciption: HM creation failed for TCP and UDP-CONNECT type
https://a10networks.atlassian.net/browse/STACK-1979
It is degraded by STACK-1654, in patch of STACK-1654 didn't consider TCP and UDP-CONNECT types.
So, this patch we will check url-type and url-path before using it in directory. Because TCP and UDP-CONNECT will not have these keys in directory.
<pre>
<b>
[a10_controller_worker]
network_driver = a10_octavia_neutron_driver
[listener]
autosnat = True
conn_limit=555000
ha_conn_mirror=True
[health_monitor]
post_data = "abc=1"
[hardware_thunder]
devices = [
{
"project_id": "3d21c71c4e4040599933bda62a76ae2f",
"ip_address": "192.168.90.46",
"username": "admin",
"password": "a10",
"device_name": "ytsai-Thunder"
}
]
</b>
</pre>
1. create hm for TCP
2. create hm for UDP …
=> Issue/stack 1979 [healthmonitor_degrade] failed to create hm with protcol type TCP or UDP-CONNECT

acos_client/v30/slb/virtual_port.py
- Severity Level: High
- Issue description: For TERMINATED_HTTPS protocol listener, the protocol on Thunder vport is https. User TERMINATED_HTTPS as protocol in axapi URI Thunder can't find the vport instance on thunder.
https://a10networks.atlassian.net/browse/STACK-2025
If protocol is TERMINATED_HTTPS, change to https in axapi URI.
<pre>
<b>
{ 
"nat-pool":{ 
"pool-name":"pool1", 
"start-address":"192.168.90.201", 
"end-address":"192.168.90.210", 
"netmask":"/24", 
"gateway":"192.168.90.1" 
}, 
"nat-pool-list":[ 
{ 
"pool-name":"pool2", 
"start-address":"192.168.90.211", 
"end-address":"192.168.90.220", 
"netmask":"/24", 
"gateway":"192.168.90.1" 
}, 
{ 
"pool-name":"pool3", 
"start-address":"192.168.90.221", 
"end-address":"192.168.90.230", 
"netmask":"/24", 
"gateway":"192.168.90.1" 
} …
=> [STACK-2025] Bug fix axapi URI for TERMINATED_HTTPS vport

acos_client/v30/action.py
- Severity Level: High
- Description:
1. Detect thunder reload and mark ERROR for loadbalancers which has lost configration. (STACK-2027)
**see also : https://github.com/a10networks/a10-octavia/pull/308**
https://a10networks.atlassian.net/browse/STACK-2027
[STACK-2027]
1. Following aXAPI can show a10lb up time, maybe we can use it to compare with update_at to find reloaded/rebooted thunders. ```/axapi/v3/miscellenious-alb/oper```
2. After find reloaded thunders, mark loadbalancers status as ERROR.
<pre>
<b>[a10_house_keeping]
use_periodic_write_memory = 'enable'
write_mem_interval = 600
</b>
</pre>
- Test reload thunders before write memory period
- create 5 loadbalancers and wait write memory
- set 2 of them
```shell
openstack loadbalancer set vip5
openstack loadbalancer set vip3
```
- …
=> [Bug] [STACK-2027] thunder reload detection

acos_client/v30/slb/hm.py
- Severity Level: Medium
- Description:
1. HTTPS POST case will failed, since in hm.py we only take care HTTP case.
https://a10networks.atlassian.net/browse/STACK-1654
Use correct aXAPI attribute for HTTP and HTTPS cases.
<pre>
<b>
[health_monitor]
post_data = "abc=1"
</b>
</pre>
- Test HTTPS POST case for HM
```shell
openstack loadbalancer create --vip-subnet-id f25ce642-f953-4058-8c46-98fdd72fb129 --vip-address 192.168.91.56 --name vip1
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name vport1 vip1
openstack loadbalancer pool create --protocol HTTP --lb-algorithm ROUND_ROBIN --listener vport1 --name sg1
openstack loadbalancer healthmonitor create --delay 7 --timeout 6 --max-retries 3 --http-method POST --type HTTPS sg1 --name hm1
```
- result:
```shell …
```
=> [Bug] [STACK1-1654] HM failed with HTTPS POST case

acos_client/v21/axapi_http.py, acos_client/v30/axapi_http.py, requirements.txt
See also a10-octavia side changes:
https://github.com/a10networks/a10-octavia/pull/333
Result:
```shell
stack@ytsai-victoria:~/source/acos-client/victoria$ sudo tox -e py38
py38 develop-inst-noop: /opt/stack/source/acos-client/victoria
py38 installed: -e git+git@github.com:ytsai-a10/acos-client.git@291bab52a63819a917c4ec57a16a909be8b6595c#egg=acos_client,appdirs==1.4.3,CacheControl==0.12.6,certifi==2019.11.28,chardet==3.0.4,colorama==0.4.3,contextlib2==0.6.0,distlib==0.3.0,distro==1.4.0,flake8==2.2.4,hacking==0.10.3,html5lib==1.0.1,idna==2.8,ipaddr==2.2.0,lockfile==0.12.2,mccabe==0.2.1,msgpack==0.6.2,packaging==20.3,pbr==5.5.1,pep517==0.8.2,pep8==1.5.7,progress==1.5,pyflakes==0.8.1,pyparsing==2.4.6,pytoml==0.1.21,requests==2.25.1,responses==0.12.1,retrying==1.3.3,six==1.15.0,uhashring==2.0 …
```
=> [STACK-2162] acos-client for victoria

acos_client/v30/action.py, requirements.txt, tox.ini
- Added a method `probe_network_devices` to execute "system probe-network-devices" on vThunder.
- Added a method `get_acos_version` to get acos_version of a vThunder.
https://a10networks.atlassian.net/browse/STACK-2155
https://github.com/a10networks/a10-octavia/pull/334
=> STACK[2015][Dynamic Interface Attachment]: Support dynamic interface attachment detection

acos_client/v30/action.py
Added API `reload_reboot_for_interface_detachment()` to perform reload/reboot on vthunder for interface detachment detection depending on the vthunder's acos_version
https://a10networks.atlassian.net/browse/STACK-2157
https://a10networks.atlassian.net/browse/STACK-2158
=> STACK-2015: Dynamic Interface Detachment Detection Support

acos_client/v30/action.py, requirements.txt
Added following APIs to support dynamic interface attachment and detachment:
**get_acos_version()**:  For getting acos_version of the vThunder device
**probe_network_devices()** : For detecting the attached interfaces(for ACOS version >= 5.2.0) and detached interfaces(for ACOS version >= 5.2.1)
**reload_reboot_for_interface_attachment()**: For performing reload or reboot on vThunder depending on the ACOS version check during interface attachment.
**reload_reboot_for_interface_detachment()**: For performing reload or reboot on vThunder depending on the ACOS version check during interface detachment.
https://a10networks.atlassian.net/browse/STACK-2015
https://github.com/a10networks/a10-octavia/pull/344
=> [Feature][STACK-2015][Dynamic Interface Detection]: Support for Dynamic Interface Detection after loadbalancers and members creation and deletion.

acos_client/errors.py, acos_client/tests/unit/v30/test_slb_aflex.py, acos_client/v30/axapi_http.py, acos_client/v30/responses.py
- Severity Level Critical
- Issue Description
In Active-Standby mode, ACOS device may busy when vcs is doing configuration sync, negotiation or reloading.
And this may happens at any time, Therefore,  there is no way to prevent it in a10-octavia. 
So, it is better we handle "System is busy" issue in acos-client.
https://a10networks.atlassian.net/browse/STACK-2301
In active-standby mode, after reload/reboot, vcs reload or vcs configuration sync. check device is up and vcs ready after sleep.
<pre>
<b>[vthunder]
default_vthunder_username = "admin"
default_vthunder_password = "a10"
default_axapi_version = "30"
#default_axapi_timeout = 600
[a10_controller_worker]
amp_image_owner_id = 99c9c2304f114685a32db30769c8a7e2
amp_secgroup_list = 2d0a3480-7f08-4184-b96f-c39bb444dd38
amp_flavor_id = …
=> [STACK-2301] axapi retry when ACOS System busy

acos_client/tests/unit/v30/test_bladeparam.py, acos_client/tests/unit/v30/test_dns.py, acos_client/tests/unit/v30/test_interface.py, acos_client/tests/unit/v30/test_vlan.py, acos_client/tests/unit/v30/test_vrrpa.py, acos_client/v30/axapi_http.py, acos_client/v30/base.py
**acos-client side PR: https://github.com/a10networks/acos-client/pull/340**
**a10-octavia side PR: https://github.com/a10networks/a10-octavia/pull/363**
If Bug Fix:
- Required: Severity Level Low
- Required: Issue Description:  Failed to create LB for public-subnet
According to the audi log:
```
vThunder(NOLICENSE)#show audi
Apr 13 2021 10:46:53  [admin] axapi: [7:192.168.0.127:34384] RESP HTTP status 400  Bad Request : Failed to acquire a DHCP offer from DHCP server.
Apr 13 2021 10:46:53  [admin] axapi: [7:192.168.0.127:34384] payload section 1
{"ethernet": {"action": "enable", "ip": {"dhcp": 1}, "ifnum": "1", "name": "DataPort"}}
Apr 13 2021 10:45:50  [admin] axapi: [7:192.168.0.127:34384] POST: /axapi/v3/interface/ethernet/1
```
- **Root Cause:**
1. The acos-client timeout is 30 …
=> [STACK-2220] acos-client timeout too short

acos_client/tests/unit/v30/test_slb_aflex.py, acos_client/v30/axapi_http.py
Fix degrade which caused by https://github.com/a10networks/acos-client/pull/341
The l7policy can't be create correctly since script content didn't import to ACOS.
This is caused by https://github.com/a10networks/acos-client/pull/341 which we  wrap the request() API but some parameter is missing while we wrap the API.
=> [STACK-2302] Fix aFlex script import failed

acos_client/v30/axapi_http.py
If Feature Addition:
- Required: Related user story
If Bug Fix:
- Required: Severity Level High
- Required: Issue Description
1. check the journal log on QA's server, when a10-octavia try to plug interface and reload on backup vthunder (i.e. AmphoraePostVIPPlug()), the backup vthunder is not up (maybe reloaded by configuration sync. or vcs). So, acos-client failed to connect ot vthunder and raise ConnectionError.
Journal log:
```shell
May 10 18:22:50 qa-109 a10-octavia-worker[28974]: DEBUG acos_client.v30.axapi_http [-] axapi_http: POST url = /axapi/v3/auth {{(pid=29014) request_impl /opt/stack/acos-client/acos_client/v30/axapi_http.py:76}}
May 10 18:22:50 qa-109 a10-octavia-worker[28974]: DEBUG acos_client.v30.axapi_http [-] axapi_http: params = {
May 10 18:22:50 qa-109 …
```
=> [STACK-2313] backup plug interface failed because of reloading

acos_client/v30/axapi_http.py, acos_client/v30/responses.py
If Bug Fix:
- Severity Level High
- Issue Description
1. acos-client may takes longer than 300 second for retry.
2. And after acos-client retry, a10-octavia still do another round of retry. And cause the retry takes very very long.
a10-octavia PR: https://github.com/a10networks/a10-octavia/pull/428
https://a10networks.atlassian.net/browse/STACK-2356
1. change acos-client retry mechanism to use time.time() to calculate actual retry time.
2. in a10-octavia, when acos-client already do the retry then adjust retries correctly.
**This is only required if the config has been updated in this PR**
- Required: Provide example config snippet within pre block
<pre>
<b>
[a10_controller_worker]
amp_active_retries = 59
amp_active_wait_sec = 10
amp_vcs_retries = 59
amp_vcs_wait_sec = 10
</b>
</pre>
1. …
=> [STACK-2356] a10-octavia retry too long

acos_client/tests/unit/test_utils.py, acos_client/utils.py, acos_client/v30/action.py
Added a new API reload_all() for supporting dynamic interface detection enhancement.
https://github.com/a10networks/a10-octavia/pull/480
https://a10networks.atlassian.net/browse/STACK-2473
https://a10networks.atlassian.net/browse/STACK-2474
- Added a new API reload_all() for reloading all devices in a cluster at a time.
- Modified reload_reboot_for_interface_attachment() and reload_reboot_for_interface_detachment() to use new API (to replace self.reload()) to reload_all VCS cluster devices.
=> [STACK-2322]: Dynamic Interface Detection Enhancement

acos_client/client.py, acos_client/errors.py, acos_client/v30/dns.py, acos_client/v30/glm/flexpool.py, acos_client/v30/glm/license.py, acos_client/v30/glm/proxy.py, acos_client/v30/license_manager.py
While the acos-client previously had support for the "pay-go" licensing model, this PR adds endpoints required to support the "Capacity Flexpool" model.
For further details please see https://github.com/a10networks/a10-octavia/pull/487
=> [STACK-2610] Add support for capacity flexpool

acos_client/v30/dns.py, acos_client/v30/glm/flexpool.py
Severity: High
Description: The secondary dns delete call was being performed before the primary. Fixed by swapping order of calls.
=> [STACK-2769] Secondary DNS is deleted before primary

acos_client/errors.py, acos_client/v30/responses.py
The ConfigManagerNotReady exception shares it's error code with exceptions caused by license requests with unpurchased license options. This results in the retry logic for the config manager to be called thus locking the execution for 2 minutes (5 second wait 24 times).
A new error has been added and is called whenever an exception with error code 4294967295 is raised during a request to the glm endpoint.
=> [STACK-2922] Setting burst to enabled on a non-burst license cause system freeze

acos_client/v30/glm/proxy.py
**Severity**: High
**Description**: vthunder devices are not getting configured with GLM proxy-server configurations. 
The request payload for create API  '/axapi/v3/glm/proxy-server' is not correct.
**Provided**
```
{
"username": "string",
"uuid": "string",
"encrypted": "Unknown Type: encrypted",
"host": "string",
"password": 0,
"port": 0,
"secret-string": "string"
}
```
**Expected:**
```
{
"proxy-server": {
"username": "string",
"uuid": "string",
"encrypted": "Unknown Type: encrypted",
"host": "string",
"password": 0,
"port": 0,
"secret-string": "string"
}
}
```
=> [BUG][STACK-2996]: [Flexpool Integration]Proxy Server configurations not getting pushed on vthunder devices. 

acos_client/v30/glm/flexpool.py
Previously the acos-client glm flexpool `_set` method had returned two values. However, that was alerted in patch and the change was not propagated to the replace/update methods. This resulted in issues with enabling bursting via the update method
Please see https://github.com/a10networks/a10-octavia/pull/554 for futher details
=> [STACK-3126] Burst is not enabled when set in the a10-octavia config

acos_client/v30/slb/hm.py
[Description]
Health Monitor with PING type creation will failed with the patch of STACK-3171
We need to take care ICMP/PING type health monitor case in acos-client. since it don't have port or overwrite port.
---
[LOG]
**- openstack**
```
stack@ytsai-victoria:~/source/a10-octavia/Fully_Polulated_LB$ openstack loadbalancer healthmonitor create --delay 30 --timeout 3 --max-retries 3 --type PING --name hm1 pool1
+---------------------+--------------------------------------+
| Field               | Value                                |
+---------------------+--------------------------------------+
| project_id          | ecc2542be2644881b049636b719ca536     |
| name                | hm1                                  |
| admin_state_up      | True                                 |
| pools …
```
=> [STACK-3171] Handle HealthMonitor PING case

acos_client/v30/slb/hm.py
[Description]
Health Monitor with PING type creation will failed with the patch of STACK-3171
We need to take care ICMP/PING type health monitor case in acos-client. since it don't have port or overwrite port.
---
[LOG]
**- openstack**
```
stack@ytsai-victoria:~/source/a10-octavia/Fully_Polulated_LB$ openstack loadbalancer healthmonitor create --delay 30 --timeout 3 --max-retries 3 --type PING --name hm1 pool1
+---------------------+--------------------------------------+
| Field               | Value                                |
+---------------------+--------------------------------------+
| project_id          | ecc2542be2644881b049636b719ca536     |
| name                | hm1                                  |
| admin_state_up      | True                                 |
| pools …
```
=> Merge master to stable/victoria for some patch bug fixing related to STACK-3171

acos_client/v30/slb/aflex_policy.py
Per the Octavia API documentation, it supports the ability to create a fully populated loadbalancer, a single request with the VIP, listener, pool, members, and health checks all in one single request sent to the Octavia api.
The current Openstack Cloud Controller Manager code (used for Kubernetes support) as of 1.21 uses fully populated load balancers for initial service creations by default. However, 1.20 did not support using providers other than “Octavia” or “amphora” so that code doesn’t work for us, our users are currently on 1.19.
Our users can’t use the latest code or send POST requests with fully populated load balancers despite the Octavia documentation telling them its supported, if they do there isn’t any sort of error or response to the user/API.  Instead, the load balancer …
=> [STACK-3250] Fully Populated Loadbalancer Create

acos_client/v30/slb/server.py
- Required: Severity Level: Critical
- Required: Issue Description:
Health Monitor will not configured on slb servers if Health Monitor creation command is after the member creation commands.
This is introduced after: https://github.com/a10networks/a10-octavia/pull/560/files
Previously we have logic to update service-group health monitor. But when move hm from service-group to slb server. We didn't implement the logic for membre.
https://a10networks.atlassian.net/browse/STACK-3375
For CreateAndAssociateHealthMonitor(), we need to update members in the pool with the health monitor.
<pre>
<b>N/A</b>
</pre>
- verify commands:
```
openstack loadbalancer create --vip-subnet-id tp91 --name vip1
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name vport1 vip1 …
```
=> [STACK-3375] Fix health monitor missing

acos_client/v30/slb/hm.py
Servility: Hight
Description: acos-client Health Monitor use a global _method_objects dictionary for all hm request. And every request will change it. There are two issue for this:
- previous request parameter still keep in it. and
- it is not thread-safe, if 2 request running at the same time. Two operation will both make change on it and the result it unpredictable. 
Issue: https://a10networks.atlassian.net/browse/STACK-3374
Solution:
- when init the param, return a copy of _method_objects intead of a _method_objects reference.
Test:
1. run the script:
```
#!/bin/sh
set -e
subnet_id=$(openstack subnet show tp91 -c id -f value)
TOKEN=$(openstack token issue -f value -c id)
OCTAVIA_BASE_URL=$(openstack endpoint list --service load-balancer --interface public -c URL -f value)
cat <<EOF > …
```
=> [STACK-3374] health monitor request may affected by previous operation

acos_client/v30/action.py
- Severity Level: Critical
- Issue Description:
- IPv6 interfaces not enabled
- Failed to configure IPv6 interface for member/LB delete case.
a10-octavia changes: https://github.com/a10networks/a10-octavia/pull/604
https://a10networks.atlassian.net/browse/STACK-3637
https://a10networks.atlassian.net/browse/STACK-3639
1. enable ipv6 interfaces
2. Clear all unmatched ipv6 addresses for all interfaces before configure ipv6 address.
Please check bug tickets
```
openstack loadbalancer create --vip-subnet-id tp91 --name vip1
openstack loadbalancer listener create --protocol TCP --protocol-port 80 --name vport1 vip1
openstack loadbalancer pool create --protocol TCP --lb-algorithm ROUND_ROBIN --listener vport1 --name sg1
openstack loadbalancer member create --address 192.168.92.24 --subnet-id …
```
=> [STACK-3637][STACK-3639] vthunder IPv6 interface and address issues
